### ISSUE TITLE
Rotations are irregularly numbered 

### ISSUE THREAD

**Issue by crw** [joyvuu-dave/comeals-ui#11]
See the attached screenshots. 

46 to 48

<img width="314" alt="Screen Shot 2020-03-01 at 12 54 36 PM" src="https://user-images.githubusercontent.com/57712/75634879-596a1c80-5bc6-11ea-8aea-e80dfc1baf89.png">

48 to 82

<img width="1352" alt="Screen Shot 2020-03-01 at 12 53 41 PM" src="https://user-images.githubusercontent.com/57712/75634884-5e2ed080-5bc6-11ea-8d83-7c6c0f9b1e32.png">

82 to 84

<img width="215" alt="Screen Shot 2020-03-01 at 12 53 51 PM" src="https://user-images.githubusercontent.com/57712/75634883-5cfda380-5bc6-11ea-8d49-34d1fd0c4e75.png">

84 to 93

<img width="203" alt="Screen Shot 2020-03-01 at 12 54 15 PM" src="https://user-images.githubusercontent.com/57712/75634881-5bcc7680-5bc6-11ea-91ac-8974837b217d.png">

**Comment by joyvuu-dave** [comment]
I think this might have been a database issue. As far as I know, there weren't any code changes that would make this happen. I could probably fix the numbers manually if this was something people were relying on.

**Comment by crw** [comment]
It is pretty distracting. If it could be fixed that would be best I think.

**Comment by joyvuu-dave** [comment]
Fixed.
